apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://gitlab.com/ocp-demo/backend_quarkus'
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: App-X
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: '11'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: backend
        image: quay.io/voravitl/backend:native
        imagePullPolicy: IfNotPresent
        env:
          - name: APP_BACKEND
            value: https://httpbin.org/delay/5
          - name: APP_VERSION
            value: v2
          - name: quarkus.log.console.color
            value: 'false'
        ports:
        - containerPort: 8080
      terminationGracePeriodSeconds: 10
