apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-app-alert
  namespace: project1
  #labels:
  #  Prometheus instance in the openshift-user-workload-monitoring project => not alert by alert manager
  #  openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
spec:
  groups:
  - name: backend-app
    rules:
    - alert: ConcurrentBackend
      expr: sum(avg_over_time(application_com_example_quarkus_BackendResource_concurrentBackend_current[1m]))>15
      for: 1m
      labels:
        severity: 'warning'
        receiver: 'line'
      annotations:
        description: 'Total concurrent request is {{ $value }} request/sec'
        summary: 'Concurrent request to backend-app is exceeded threshold'
    - alert: HighLatency
      expr: quantile_over_time(0.9,application_com_example_quarkus_BackendResource_timeBackend_mean_seconds[1m])>5
      for: 1m
      labels:
        severity: 'critical'
        receiver: 'line'
      annotations:
        description: '{{ $labels.pod }} response time is {{ $value }} sec'
        summary: 'Response time of backend-app is exeeded threshold'
